version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest  # SQL Server image
    container_name: Ordersqlserver
    ports:
      - "1433:1433"  # Expose SQL Server's port
    environment:
      SA_PASSWORD: "SamerPass.123"  # Set the SA password
      ACCEPT_EULA: "Y"  # Accept the EULA
    volumes:
      - sqlserver_data:/var/opt/mssql  # Persist database data in a volume

  bookingserviceapi:
    build:
      context: .  # Build the Docker image from the current directory
      dockerfile: OrderService/Dockerfile  # Path to your Dockerfile
    container_name: OrderService
    ports:
      - "8080:8080"  # Expose your API on port 8080
    depends_on:
      - sqlserver  # Ensure SQL Server starts first
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=OrderDB;User Id=sa;Password=SamerPass.123;TrustServerCertificate=True;"  # Connection string to SQL Server

volumes:
  sqlserver_data:  # Define the volume to persist SQL Server data